input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [level] {
    mutate {
      add_field => { "log_level" => "%{level}" }
    }
  }

  if [service] {
    mutate {
      add_field => { "service_name" => "%{service}" }
    }
  }

  date {
    match => ["timestamp", "ISO8601"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "scirm-logs-%{+YYYY.MM.dd}"
  }
}
